/**
 * "1，type:hidden字段需要废弃掉但是需要兼容，每个元素是否隐藏需要看是否配置hidden属性为true来决定",
 * 2，
 * */
export default {
  formStyle: 'normal',
  groups: [
    {
      name: 'Group A',
      describe: 'descrition of Group A',
      list: [
        {
          id: 'name',
          type: 'text',
          label: '名字',
          isEdit: 1,
          value: '',
        },
        {
          id: 'sex',
          type: 'select',
          label: '性别',
          isEdit: 1,
          value: '男',
          options: ['男', '女'],
        },
        {
          id: 'photos',
          type: 'select',
          label: '照片',
          isEdit: 1,
          value: '',
          options: [],
          getOptions: 'sex',
        },
      ],
    },
    {
      name: 'Group A',
      describe: 'descrition of Group A',
      list: [
        {
          id: 'age',
          type: 'text',
          label: '年龄',
          isEdit: 1,
          value: '',
        },
        {
          id: 'job',
          type: 'text',
          label: '职业',
          isEdit: 1,
          value: '',
          displayWithRule: 2,
          displayWith: [
            {
              field: 'age',
              values: ['18', '19', '20'],
            },
            {
              field: 'photos',
              values: ['showjob'],
            },
          ],
        },
      ],
    },
    // {
    //   groupName: '不同的selectBiz业务类型选择',
    //   describe:
    //     'reqOnSave字段标识新增时必填，req表示提交时必填，所以会有一个校验函数来取不同的标志校验内容',
    //   list: [
    //     {
    //       describe:
    //         'unEditHasDetail字段就是取当前详情的数据如果在详情字段里面能去掉对应配置的值，标记当前字段不可编辑',
    //       label: '对应合同',
    //       isEdit: 1,
    //       type: 'selectBiz',
    //       name: '合同',
    //       text: '',
    //       value: '',
    //       placeholder: '请选择合同',
    //       id: 'contract_id',
    //       cols: 1,
    //       reqOnSave: 1,
    //       unEditHasDetail: 'history_id',
    //       errMsg: {
    //         req: '对应合同不能为空',
    //       },
    //     },
    //     {
    //       label: '三方甲指合同',
    //       isEdit: 1,
    //       type: 'selectBiz',
    //       text: '',
    //       value: '',
    //       reqOnSave: 1,
    //       placeholder: '请选择合同',
    //       id: 'jzc_contract_id',
    //       req: 0,
    //       cols: 1,
    //       options: '',
    //     },
    //   ],
    // },
    // {
    //   groupName: '下拉选择',
    //   describe:
    //     '包括select，relative_select，group_select, multi_select,下拉的值来源于contract_id数据冲后台拉取，如果当前字段配置options为数组则直接取配置的数组值作为下拉，如果配置的是字符串用这个字符串做key取contract_id拉取过来的数据',
    //   list: [
    //     {
    //       label: '变更类型',
    //       isEdit: 0,
    //       type: 'relative_select',
    //       text: '',
    //       value: '',
    //       placeholder: '必选',
    //       options: 'change_type',
    //       id: 'change_type',
    //       req: 1,
    //       describe: '父子选择',
    //       childId: 'change_reason',
    //       isSave: 1,
    //       defaultValue: '@from_url',
    //     },
    //     {
    //       label: '变更原因',
    //       isEdit: 1,
    //       describe: '父子选择',
    //       type: 'relative_select',
    //       text: '',
    //       value: '',
    //       placeholder: '必选',
    //       id: 'change_reason',
    //       req: 1,
    //       parentId: 'change_type',
    //     },
    //     {
    //       label: '结算类型',
    //       isEdit: 1,
    //       isSave: 1,
    //       describe: '二级选择',
    //       type: 'group_select',
    //       placeholder: '必选',
    //       options: 'settlement_type',
    //       id: 'settlement_type_id',
    //       groupId: 'settlement_type',
    //       req: 1,
    //     },
    //     {
    //       label: '涉及专业',
    //       isEdit: 1,
    //       type: 'multi_select',
    //       describe: '多选',
    //       text: '',
    //       placeholder: '非必选',
    //       options: 'major',
    //       id: 'major',
    //       req: 0,
    //     },
    //   ],
    // },
    // {
    //   groupName: '指定selectBiz数据填充表单',
    //   describe:
    //     'relative_id指定数据来源，nestingStructure指定层级数据匹配，支持模糊匹配',
    //   list: [
    //     {
    //       label: '供货商名称',
    //       isEdit: 0,
    //       type: 'text',
    //       cols: 1,
    //       text: '',
    //       value: '',
    //       placeholder: '',
    //       id: 'jzc_yf_company',
    //       nestingStructure: 'jzc_contract_info.yf_company',
    //       relative_id: 'jzc_contract_id',
    //       req: 0,
    //     },
    //     {
    //       label: '施工单位名称',
    //       isEdit: 0,
    //       type: 'text',
    //       cols: 1,
    //       text: '',
    //       value: '',
    //       placeholder: '',
    //       id: 'yf_company',
    //       nestingStructure: 'yf_company',
    //       relative_id: 'contract_id',
    //       options: '',
    //       req: 0,
    //       maxLength: 100,
    //     },
    //   ],
    // },
    // {
    //   groupName: '动态计算，动态校验，动态模板',
    //   describe:
    //     'calc_method计算表单式，替换对应的值执行eval,calc_fail_value计算出错默认值，validate值变化校验内容, template直接替换值不需要计算',
    //   list: [
    //     {
    //       id: 'send_quantity',
    //       type: 'text',
    //       isEdit: 1,
    //       label: '送货数量',
    //       text: '',
    //       value: '',
    //       maxLength: 100,
    //       cols: 1,
    //       req: 1,
    //     },
    //     {
    //       id: 'receive_quantity',
    //       type: 'text',
    //       isEdit: 1,
    //       label: '实际签收数量',
    //       text: '',
    //       value: '',
    //       maxLength: 100,
    //       cols: 1,
    //       req: 1,
    //     },
    //     {
    //       id: 'receive_quantity_send_quantity',
    //       type: 'hidden',
    //       isEdit: 0,
    //       label: '实际签收数量',
    //       text: '',
    //       value: '',
    //       maxLength: 100,
    //       calc_method: '{{send_quantity}} - {{receive_quantity}}',
    //       calc_fail_value: 0,
    //       validate: {
    //         minValue: {
    //           value: 1,
    //           errMsg: '签收数量需要小于送货数量',
    //         },
    //       },
    //       cols: 1,
    //       req: 0,
    //     },
    //     {
    //       id: 'receive_quantity_send_quantity1',
    //       isEdit: 0,
    //       label: '实际签收数量',
    //       text: '',
    //       value: '',
    //       maxLength: 100,
    //       template: '{{send_quantity}} - {{receive_quantity}}',
    //       cols: 1,
    //       req: 0,
    //     },
    //   ],
    // },
    // {
    //   groupName: '动态显隐',
    //   describe:
    //     'displayWith用来标记元素动态显示隐藏的规则，displayWithRule配置与或规则，type字段标记数据来源表单中还是用户信息',
    //   list: [
    //     {
    //       label: '变更审核金额',
    //       isEdit: 0,
    //       type: 'money',
    //       id: 'reviewed_cost',
    //       units: {
    //         text: '元',
    //       },
    //       displayWithRule: 1,
    //       displayWith: [
    //         {
    //           field: 'check_status',
    //           values: ['3'],
    //         },
    //         {
    //           type: 'user',
    //           field: 'role_code',
    //           values: ['998', '999', '1000', '1002', '1003', '2001'],
    //         },
    //       ],
    //     },
    //     {
    //       label: 'check_status',
    //       isEdit: 0,
    //       type: 'text',
    //       id: 'check_status',
    //     },
    //   ],
    // },
  ],
}
